Work 2709
fd1-44-17-group/kirillunited pull request #14
Opened 2017-09-28 18:24 UTC by KirillUnited

@fd1-44-17 please review

2017-09-29 05:16 UTC, fd1-44-17 requested changes

2017-09-29 05:16 UTC, fd1-44-17 commented on work/27-09/2/index.html
> +    <p>Первая сборка с <span style="background-color: lightgrey; padding: 2px; border: 1px solid #A9A9A9; border-radius: 5px;"><code>bem tools</code></span> займёт некоторое время, так как именно в э
потеряли дефис.

2017-09-29 05:16 UTC, fd1-44-17 commented on work/27-09/2/index.html
> +    <div style="overflow: auto;
стилей в аттрибутах быть не должно. Все должно быть вынесено в css-файл.

2017-10-01 01:17 UTC, KirillUnited commented
@fd1-44-17 please review

2017-10-05 12:01 UTC, fd1-44-17 approved these changes

2017-10-05 12:01 UTC, merged