Dz 0409
fd1-44-17-group/kirillunited pull request #2
Opened 2017-09-06 07:33 UTC by KirillUnited

@fd1-44-17

2017-09-06 07:34 UTC, KirillUnited commented
@fd1-44-17 
please review

2017-09-07 05:49 UTC, fd1-44-17 requested changes
Кавычки!

2017-09-07 05:49 UTC, fd1-44-17 commented on dz/dz1/diary.html
> +    <h3 align=center>Дневник партизана</h3>
Где кавычки?

2017-09-07 05:49 UTC, fd1-44-17 commented on dz/dz1/diary.html
> +    &copy; бородатый <a href='http://anekdotov.net/anekdot/' target='_blank'>анекдот</a>
Почему тут одинарные, а в теге meta - двойные?

2017-09-07 05:49 UTC, fd1-44-17 commented on dz/dz2/diary2.html
> +    &copy; бородатый <a href='http://anekdotov.net/anekdot/' target='_blank'>анекдот</a>
почему тут одинарные кавычки?

2017-09-07 05:49 UTC, fd1-44-17 commented on dz/dz2/diary2.html
> +        <li><b>Вторник.</b> Выбили <a href='https://ru.wikipedia.org/wiki/%D0%9D%D0%B5%D0%BC%D1%86%D1%8B' target='_blank'>немцев</a> с опушки.
то же самое

2017-09-07 12:53 UTC, KirillUnited commented
@fd1-44-17
please review

2017-09-08 05:12 UTC, fd1-44-17 approved these changes

2017-09-08 05:12 UTC, merged